# Configurations for HuRAG WebUI application

# MariaDB/MySQL database connector
mariadb:
  host:       localhost
  port:       3306
  user:
  password:
  database:   hurag_webui

# Dependencies
services:
  sso:
  ctx_size:   tiny  # tiny or medium or large

